### ISSUE TITLE
Missplaced images and impossible to scale the window

### ISSUE THREAD

**Issue by misiakpol** [solleo1989/SwitchCheatCodeManager#3]
Like the title says, something is wrong with the icons, and the whole formatting for the window which is making impossible to see sections as per the image below. Are there any prerequisites? I have Java so no other idea

![image](https://user-images.githubusercontent.com/106669997/224969550-e3beefdf-daf8-483c-87be-c7607770e724.png)

**Comment by solleo1989** [comment]
From your screenshot, the resolution seemed below 1080p even. This might be a bug for <1080p users, I only wrote it for myself (didn't expect for public release). 
Hotfitx: You can simply Right click the app(.exe) > Properties, and check as the screenshot. 
![image](https://user-images.githubusercontent.com/5420867/225707921-98559d33-ee73-4222-a6a0-5c23100fc1e4.png)
It should be fixed.

**Comment by solleo1989** [comment]
1080P
![image](https://user-images.githubusercontent.com/5420867/225708308-4bbcd5c6-f89c-47f9-bce7-0e72ea9896cd.png)

Change Properties > High DPI settings
![image](https://user-images.githubusercontent.com/5420867/225708499-3f794e8b-8ff7-4a4c-8211-5728d56d2677.png)

Upscalling 
![image](https://user-images.githubusercontent.com/5420867/225708618-37c510c8-b226-4e27-830a-3beed57af320.png)

**Comment by Ninjistix** [comment]
having this similar issue with windows 11, and changing these settings doesn't work.

edit: my resolution is 

![image](https://github.com/solleo1989/SwitchCheatCodeManager/assets/12572974/47a2d3c6-05bb-474c-8948-11b52d2b7738)

**Comment by solleo1989** [comment]
> having this similar issue with windows 11, and changing these settings doesn't work.
> 
> edit: my resolution is
> 
> ![image](https://user-images.githubusercontent.com/12572974/242003609-47a2d3c6-05bb-474c-8948-11b52d2b7738.png)

1440p shouldn't be any issue, unless you modified some other stuffs.

Here's the 2k setup on my pc:
![image](https://github.com/solleo1989/SwitchCheatCodeManager/assets/5420867/5cd26cdd-fa8c-4e5e-93fc-03c7c6fa430d)
