### ISSUE TITLE
.net (windows 11)

### ISSUE THREAD

**Issue by Ninjistix** [solleo1989/SwitchCheatCodeManager#4]
is it possible to update the .net target?

![image](https://github.com/solleo1989/SwitchCheatCodeManager/assets/12572974/2e8acec1-2e79-481b-8855-2e28fcdc3df4)

clicking yes dose nothing, and manually downloading the .net desktop runtime 6.0.3 also gives me this same error after installation.

**Comment by solleo1989** [comment]
This is totally required by Microsoft. Same error means you didn't install correctly, maybe installed 32bit ?

**Comment by Ninjistix** [comment]
no I grabbed the x64 from here, https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.3-windows-x64-installer

I managed to get it open, but I'm having some issues with resizing the window
